### 1. Testar Saúde da API
GET http://localhost:3333/health

###

### 2. Criar Usuário
# @name createUser
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Maria Silva",
  "email": "maria@vessel.com",
  "role": "GUEST"
}

###

### 3. Listar Usuários
GET http://localhost:3333/users

###

### 4. Criar Propriedade
POST http://localhost:3333/properties
Content-Type: application/json

{
  "title": "Apartamento na Praia",
  "description": "Vista para o mar com 2 quartos",
  "pricePerNight": 250,
  "location": "Rio de Janeiro",
  "maxGuests": 4,
  "hostId": "d569e2fb-1b13-4dcb-bc95-4a5f7dca1640"
}

###

### 5. Criar Reserva (com Redlock)
POST http://localhost:3333/bookings
Content-Type: application/json

{
  "userId": "d569e2fb-1b13-4dcb-bc95-4a5f7dca1640",
  "propertyId": "d0b2adb1-ecb3-478c-859f-8693643b2f39",
  "startDate": "2026-10-01T00:00:00.000Z",
  "endDate": "2026-10-05T00:00:00.000Z"
}


### 6. Consultar Disponibilidade da Propriedade
GET http://localhost:3333/properties/d0b2adb1-ecb3-478c-859f-8693643b2f39/availability


### 7. Listar Reservas do Usuário
GET http://localhost:3333/bookings/user/d569e2fb-1b13-4dcb-bc95-4a5f7dca1640


### 8. Cancelar Reserva
PATCH http://localhost:3333/bookings/4e26f53a-7e83-4aef-8920-57ebba50be6d/cancel




GET http://localhost:3333/properties
Content-Type: application/json

###

### ==========================================
### FLUXO DE AUTENTICAÇÃO E ROTAS PROTEGIDAS
### ==========================================

### 1. Autenticar Utilizador (Login)

### 0. Criar Novo Utilizador
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Marcelo Anjos",
  "email": "marcelo@vessel.com",
  "password": "suasenhasegura123"
}

###

### 1. Authenticate User (Login)
# @name login
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "marcelo@vessel.com",
  "password": "suasenhasegura123"
}


### 2. Criar Reserva (Rota Protegida com Token)
POST http://localhost:3333/bookings
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "propertyId": "d0b2adb1-ecb3-478c-859f-8693643b2f39",
  "userId": "a42cb661-74f0-4395-8b9d-c5ba3d154a16",
  "checkIn": "2026-10-10",
  "checkOut": "2026-10-15"
}